security.jwt.token.secret-key: my-secret-key

server:
  port: 7070

spring:
  datasource:
    url: jdbc:postgresql://192.168.70.87:5432/security_db
    driver-class-name: org.postgresql.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql